base:
  project: dvc_pipeline_demo1
  random_state: 47
  target_col: quality

data_source:
  # gs_path: gs://dvc_project/
  #local_path: https://raw.githubusercontent.com/TripathiAshutosh/dataset/main/red_wine.csv
  local_path: Raw_data/dataset_main_red_wine.csv

split:
  dir: data/split
  train_file: train.csv
  test_file: test.csv
  split_ratio: 0.2

process:
  dir: data/processed
  train_file: final_train.csv
  test_file: final_test.csv

train:
  n_est: 30

model_dir: model


