name: CML
on: push
permissions:
  contents: write
  pull_requests: write
  id-token: write
jobs:
  deploy-runner:
    if: github.actor == 'iterative-studio[bot]'
    environment: cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON_KEY }}
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml runner launch --single \
            --labels=cml \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=m
  runner-job:
    needs: deploy-runner
    environment: cloud
    runs-on: [ self-hosted, cml ]
    container: iterativeai/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON_KEY }}
      - name: training
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Setup project
          pip install -r requirements.txt

          cml ci --fetch-depth 0

          dvc exp run --pull --allow-missing

          dvc push

          cml pr --squash --skip-ci .

          echo "## Metrics" >> report.md
          dvc metrics diff main --md >> report.md
          echo "## Params" >> report.md
          dvc params diff main --md >> report.md

          cml comment create --pr report.md
